name: linode-cli
version: "3.1.1"
summary: "linode-cli allows you to manage your Linode account from your terminal."
description: |
  linode-cli allows you to manage your Linode account from your terminal. Create, manage, and delete Linode VPSs, domain names, and more.
grade: stable
confinement: strict
icon: icon.png

base: core18

parts:
  linode-cli:
    plugin: python
    python-packages:
      - linode-cli==$SNAPCRAFT_PROJECT_VERSION

apps:
  linode-cli:
    command: linode-cli
    plugs:
      - home
      - network
